//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class BaseItem
{
	BetterList<ItemEffect> effectList;

	public BaseItem ()
	{
	}

	public ItemEffect	GetEffect(int index)
	{
		return effectList[index];
	}

	public BetterList<ItemEffect> GetEffectList()
	{
		return effectList;
	}
}

