//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AssemblyCSharp
{
	public class Backpack : ItemContainer
	{
		public enum Slots
		{
			INVALID_BACKPACK = -1,
			BACKPACK_ACCESSORY1,
			BACKPACK_ACCESSORY2,
			BACKPACK_ACCESSORY3,
			BACKPACK_ACCESSORY4,
			BACKPACK_ITEM1,
			BACKPACK_ITEM2,
			BACKPACK_ITEM3,
			MAX_BACKPACK
		}

		int BACKPACKSIZE = 7;
		
		protected override void Initialize()
		{
			items = new List<Item> (BACKPACKSIZE);
		}
		
		public Item GetItem(Slots index)
		{
			return items[(int)index];
		}

		/// <summary>
		/// Swap the item at indexToReplace with replacingItem.
		/// Returns the item that was previously at the index.
		/// </summary>
		public Item Swap(Item replacingItem, Slots indexToReplace)
		{
			int index = (int)indexToReplace;
			Item retval = items[index];
			items[index] = replacingItem;
			return retval;
		}
	}
}

