//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AssemblyCSharp
{
	public class Inventory : ItemContainer
	{
		int INVENTORYSIZE = 12;

		protected override void Initialize()
		{
			items = new List<Item> (INVENTORYSIZE);
		}
	}
}

