//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class UITown_Panel : UIPlayerMenuPanel
{
	static float ANGLETOLERANCE = 20f;

	protected bool CloseTo(float a, float b)
	{
		return (Mathf.Abs(a - b) <= ANGLETOLERANCE);
	}
}


